language: R
sudo: required
cache: packages

r_packages:
  - rmarkdown

install:
- R -e "install.packages('devtools')"
- R -e "devtools::install_github('rstudio/rmarkdown')"
- wget https://github.com/mathjax/MathJax/archive/master.zip
- unzip master.zip >/dev/null
- rm master.zip
- export RMARKDOWN_MATHJAX_PATH=$PWD/MathJax-master

script:
- R -e "rmarkdown::render_site()"

deploy:
  provider: pages                         # Specify the gh-pages deployment method
  skip_cleanup: true                      # Don't remove files
  github_token: $GITHUB_TOKEN             # Set in travis-ci.org dashboard
  local_dir: docs                         # Deploy the docs folder
  on:
    branch: master

notifications:
  email: false
