
<!-- badges: start -->
<!-- badges: end -->

## Update 2022-05

- zpracovaná časová řada systemizace je dostupná na https://github.com/petrbouchal/systemizace
- tamtéž zpracovaná organizační struktura z open dat níže
- aktuální verze přehledové studie (Daniel Bartušek, Petr Bouchal, Petr Janský, IDEA CERGE-EI 2022) je [na webu IDEA](https://idea.cerge-ei.cz/studies/statni-zamestnanci-a-urednici-kde-pracuji-a-za-kolik-2) i s interaktivními grafy, kód na https://github.com/dan-bart/urednici_2021

## O co jde

Tento repozitář obsahuje work-in-progress sběr, přípravu a analýzu dat o českých státních úřednících.

Analýza navazuje na [studii think tanku IDEA z roku 2014 (Bouchal & Janský)](https://idea.cerge-ei.cz/studies/2014-06-statni-urednici-kolik-jich-vlastne-je-kde-a-za-jake-platy-pracuji). Natahuje časovou řadu až do roku 2018/2019 a snaží se o lepší replikovatelnost analytické práce.

Studie mj. vysvětluje seskupení veřejných organizací, za které stát sleduje počty úředníků a platové náklady a které se vyskytují i zde. 

## Data

Ke zdrojům dat viz [poznámku](zdroje-2019.html), která poslouží i jako dílčí úvod k dostupnosti administrativních dat o zaměstnancích českého státu.

## Technologie

Práce se děje v R/RMarkdown, z čehož se následně generuje i [web](https://petrbouchal.github.io/urednici/). Vše by mělo být replikovatelné z [githubového repozitáře](https://github.com/petrbouchal/urednici). 
