---
title: Jak se z oficiálních dat něco dovědět o počtech úředníků českého státu
subtitle: Edition 2018
author: Petr Bouchal
date: 23 May 2022
---

## Update 2022-05

- zpracovaná časová řada systemizace je dostupná na https://github.com/petrbouchal/systemizace
- tamtéž zpracovaná organizační struktura z open dat níže
- aktuální verze přehledové studie (Daniel Bartušek, Petr Bouchal, Petr Janský, IDEA CERGE-EI 2022) je [na webu IDEA](https://idea.cerge-ei.cz/studies/statni-zamestnanci-a-urednici-kde-pracuji-a-za-kolik-2) i s interaktivními grafy, kód na https://github.com/dan-bart/urednici_2021

# Co je potřeba

- data o počtech zaměstnanců, co nejjemnější členění (skupiny organizací => kapitoly => organizace)
- data o nákladech na platy pro výpočet a srovnání průměrných platů vzájemně a s trhem práce (tj. bez pojistného, nákladů na DPP, platy politiků atd.)

# Kde tato data vzít

## 0. Interní tabulka MF pro tvorbu SZÚ 

- Svatý Grál: všechno v jedné mega a ancient excelové tabulce:
  - počty zaměstnanců i objemy výdajů
  - 2003-201X
  - členění na skupiny reportované v SZÚ
  - všechny fáze rozpočtu
  - po kapitolách i organizacích
  - oddělené platy a ostatní platby za provedenou práci
- půjčili nám je na studii IDEA v roce 2013
- (-) děsivé vzorečky a provazby kamsi na síťový disk MF, ale snad je to správně
- ~~(-) teď už se toho nedá dobrat, nejsme schopni na MF zkontaktovat vlastníka souboru~~
- update 2021/03: z MF máme data za roky 2013-2020
- (-) neznám status té věci, proto původní soubor na Github nedávám (nic tajného tam není, ale je to něčí interní práce)

## 1. SZÚ: státní závěrečný účet

NB tento datový zdroj obsahuje určitý řez celými veřejnými financemi, tj. nejen daty o úřednících, čili poznámky i kód můžou být užitečné pro zpracování širšího spektra dat, byť ta asi budou často dostupná i v Monitoru státní pokladny. 

- obsahuje počty zaměstnanců a finanční objemy výdajů na platy - tabulky 10 a 11, tj. součást tabulkové přílohy, dá-li MF, tak v excelu
- finanční objemy pouze v součtu "Platy a ostatní platby za provedenou práci"
- to odpovídá seskupení 50 v druhovém členění, ale nejdou z toho vypočítat průměrné platy, protože ty MF v SZÚ počítá (logicky) pouze z položky platy bez "ostatních plateb za provedenou práci (OPPP)", je tedy potřeba odečíst OPPP (viz níže)
- v excelu jsou dostupné relevantní tabulky z webu Sněmovny od roku 2012 do roku 2018 (zajímavé je, že excelových souborů od roku 2012 ubývá a letos už je tam jen jeden hlavní, zbytek často jako obrázky v PDF)
  - potřeba hledat za jednotlivá volební období zvlášť
  - ve [skriptu](https://github.com/petrbouchal/urednici/blob/master/1_scrape-szu-staffreports.R) jsou zapsané přesné odkazy
- tyto tabulky mají skoro stejnou strukturu mezi lety, jdou tedy strojově zkompilovat, následně jsou uložené v původní XLS formě [na githubu](https://github.com/petrbouchal/urednici/tree/master/data-input)
- schválený rozpočet 2013 v těchto datech odpovídá schválenému rozpočtu 2013 v interní tabulce MF, kterou nám v roce 2013 laskavě půjčili
- v roce 2021 jsme dostali od MF prodlouženou verzi excelové megatabulky z toku 2013

## 2. Výkaz výdajů, druhové členění

- součást státní pokladny - jak [analytického rozhraní](http://monitor.statnipokladna.cz/analyza/) - report *Příjmy, výdaje a financování státu*, tak [hrubých open dat](http://monitor.statnipokladna.cz/2019/zdrojova-data/transakcni-data)
- pozor, analytika SP [má dostat novou verzi](https://twitter.com/otevrenadatamf/status/1190329092916289536)
- obsahuje pouze objemy výdajů, nikoli počty lidí
- OPPP zmíněné výše, které chybí ve veřejných datech SZÚ, odpovídají podseskupení 502 druhového třídění rozpočtu - složení tohoto podseskupení se mezi kapitolami liší, ale to nevadí
  - obecně obsahují odstupné apod., ale také "ostatní osobní výdaje" a "Ostatní platby za provedenou práci jinde nezařazené", přičemž to první by měly být DPP a DPČ, viz <https://ucetniportal.cz/wiki/html?item=14399>
- 501 by měly být platy, 503 a 504 jsou pojistné a další, které ve výkazu SZÚ vůbec nefigurují
- lze získat z rozhraní Monitoru SP za 2010-2019, ale u podseskupení se tam chybně místo názvu ukazují kódy, takže je to méně přehledné
- validace proti SZÚ 2013 potvrzuje, že OPPP = podseskupení 502 a Platy + OPPP = seskupení 50, tj. platy by měly jít dovodit odečtem
- to také znamená, že podseskupení platy neobsahuje platy představitelů státní moci (politici)
- nelze ověřit, jestli to platí pro 2014+
- od 2016 existuje položka na platy lidí ve státní službě a položka na ostatní
- z Monitoru jde toto vytahat na úrovni kapitol, pak už je to moc velké, ale zato v časové řadě 2010-2019, zatímco z open dat by se to muselo tahat ze dvou různých souborů pro -2014 a 2015-, ale zase by to šlo po organizacích.
- v open datech sada
  - pro -2014 FIN 204 U, výkaz/soubor FIN U 101/FIN U 102, tj. výkaz 52, tabulky 100/200/300
  - pro 2015+ FIN 112-OSS, výkaz/soubor MIS-RIS
  - číselník `polozka` pro druhové třídění
  - co rok, to datový soubor...
  - export z analytického interface per kapitola [na githubu](https://github.com/petrbouchal/urednici/tree/master/data-input

## 3. Výkaz povinných ukazatelů

- součást státní pokladny - jak analytického rozhraní, tak hrubých open dat
- pouze objemy výdajů
- relevantní jsou "průřezové ukazatele" - platí pro všechny kapitoly/organizace
- do 2014 za organizaci, od 2015 za kapitolu
- v čase se mění relevantní ukazatel (hlavně náběh SlužZ a jiné)
- ukazatele nejde mezi sebou sčítat, některé jsou podskupinou jiných
- obsahuje 
  - vždy *Platy zaměstnanců a ostatní platby za provedenou práci*
  - do 2015 Platy státních úředníků a platy zaměstnanců v pracovním poměru (státní úředníci zřejmě podle nefunkčního zákona o úřednících)
  - od 2016 *Platy zaměstnanců v pracovním poměru vyjma zaměstnanců na služebních místech* a *Platy zaměstnanců na služebních místech dle zákona o státní službě*
  - soudě dle čísel tyto ukazatele dávají smysl - např. aspoň AVČR nemá žádné lidi ve službě...
- monitorují se normálně v logice rozpočet-po změnách-konečný-výsledek
- v open datech sada
  - pro -2014 FIN 204 U, výkaz/soubor FIN U 106, tj. tabulka 700/část 7 výkazu 52
  - pro 2015+ FIN 112-OSS, výkaz/soubor MIS-RIS-ZU
  - pro ukazatele číselníky `polvkk` (do 2014) a `psuk` (2015+)
  - co rok, to datový soubor
  - export z analytického interface per kapitola [na githubu](https://github.com/petrbouchal/urednici/tree/master/data-input)

# Kategorie

TLDR: SZÚ používá v části o regulaci veřejné zaměstnanosti zvláštní kategorizaci organizací, kterou se mi nedaří replikovat z dat Státní pokladny.

Státní pokladna ale v metadatech o účetních jednotkách (účtujících organizacích) obsahuje i vlastnost Typ OSS, o které tvrdí, že je pro účely rozpočtové regulace zaměstnanosti. Školy zřizované obcemi tam ale jsou vedené jako příspěvkovky obcí, oproti kategorizaci SZÚ. Aspoň ale jde najít organizace ÚO a OSS a prokřížit se správcovstvím kapitol (poddruh ÚJ) => existují organizace, jako třeba Kancelář prezidenta, které jsou správci kapitol, ale nejsou ústředními orgány státní správy a spadají tak do typu "Ostatní OSS" i když např. s ministerstvem sdílí druh "OSS - správce kapitoly"

- http://monitor.statnipokladna.cz/2019/zdrojova-data/prohlizec-ciselniku/ucjed?date=1.11.2019
- při využití XML potřeba na číselník ucjed navázat číselníky typorg, druhuj, poddruhuj a kapitola
- bohužel nekoreluje zcela s kategoriemi v SZÚ (viz školy, netestoval jsem vojáky, hasiče atd.)

# Co tedy s tím

- vzít počty zaměstnanců ze SZÚ
  - hotovo, viz základní grafický sumář na <https://petrbouchal.github.io/urednici/2_explore-counts.html> 
  - též propojeno s podmnožinou/derivátem starších dat od MF, grafický sumář výsledku viz <https://petrbouchal.github.io/urednici/3_explore-counts-longseries.html>
- vzít celkové objemy platy+OPPP ze SZÚ
- dopočítat OPPP paralelně z výdajů a ukazatelů
- podívat se, jestli podíl OPPP na celku se mezi dvěma metodami liší a je konzistentní s minulými interními daty MF
- využít číselníky státní pokladny pro navazování a kategorizaci
  - IČO, vazba kapitola-organizace atd., názvy a kódy kapitol atd.
  - kategorizace OSS: zkusit vytvořit nějakou rozumnou kategorizaci prokřížením poddruhu ÚJ a typu organizacex
- vše napřed na úrovni kapitol s tabulkami z , pak z hrubých open dat na úrovni organizací, ale pozor na konsolidace atd.
- v prvním gardu se trápit OSS/SS/ÚO, pak až školami, hasiči, armádou a ... špiony.

# Dodatek: data o trhu práce

- pro srovnání platů jsme v roce 2013 používali tato data z ČSÚ:
  - [Evidenční počet zaměstnanců a jejich mzdy, kód 110024-19](https://www.czso.cz/csu/czso/evidencni-pocet-zamestnancu-a-jejich-mzdy-3-ctvrtleti-2019) - čtvrtletní, časová řada 2000-2018 slepená v příloze 1b, ale jen pro celou ČR; po krajích se to musí brát z jednotlivých souborů (tab 46/tab 106)
  - [Časové řady základních ukazatelů statistiky práce - leden 2020, kód 110025-19](https://www.czso.cz/csu/czso/casove-rady-zakladnich-ukazatelu-statistiky-prace-leden-2020) - krajské jen roční do 2017 a navíc neslepené. 
  
# Data ČSÚ - výběr z VDB na doporučení:

- https://vdb.czso.cz/vdbvo2/faces/cs/index.jsf?page=statistiky#katalog=30852: krajské mediány a krajské průměry (2000-2019) podle klasifikace zaměstnání (2005/2011-2018) nebo odvětví (2005-2018)
- https://vdb.czso.cz/vdbvo2/faces/cs/index.jsf?page=vyhledavani&katalog=all&vyhltext=medi%C3%A1n: krajské průměry podle klasifikace zaměstnání a pohlaví 2011-2018

Počty zaměstnanců a platy podle sektorů jsou ve [Statistické ročence ČR, kap. 10 Trh práce](https://www.czso.cz/csu/czso/10-trh-prace-o73cun42om), v roce 2020 tabulka 10A-3 "Zaměstnanci a jejich průměrné hrubé měsíční mzdy v národním hospodářství podle sektorů"

Většinou podivné rozložení políček, které by se musely exportovat po jednom kraji, roce, nebo obojí, ale lepší než nic.
  

Alternativa je vzít data z ISPV, kde je to ale poskládané ještě hůř:

- archiv https://www.mpsv.cz/web/cz/archiv-publikaci-ispv od 2000
- aktuální https://www.mpsv.cz/web/cz/publikace-ispv-ke-stazeni
- cesta k xlsx mzdové a platové sféry dohromady https://www.mpsv.cz/documents/20142/636498/ISPV_{NNN}.xlsx kde 004 < NNN < 194
NB je potřeba zaznamenat přesný kód produktu, tabulku i údaje. Do 104 (2010 Q4) jsou jen ZIP soubory, ve kterých je zvlášť excel za mzdovou a platovou sféru.
- krajská data od 2001 https://www.mpsv.cz/web/cz/porovnani-kraju např. https://www.mpsv.cz/web/cz/hlavni-mesto-praha, URL na excel např. https://www.mpsv.cz/documents/20142/848077/pra_012_ps.xls, kde NNN jsou jiná čísla než u celorepublikových dat ISPV. Od 2011 snad ve stejné formě. Existuje i porovnání krajů (což jsou ale jen excely krajů v jednom ZIP, pokud správně vidím, navíc je tam často jen podnikatelská/mzdová sféra).

# Státní rozpočet

- měl by obsahovat to co SZÚ, každopádně od 2015 je v [excelu v open datech MF](https://data.mfcr.cz/cs/dataset/statni-rozpocet)

- pokladní plnění excely např. https://www.mfcr.cz/assets/cs/media/Pokladni-plneni_2020-03_Tabulka-mesicni-pokladni-plneni-03-2020.xlsx, odkaz z https://www.mfcr.cz/cs/aktualne/tiskove-zpravy/2020/pokladni-plneni-sr-38056 a URL má stejnou formu ve 2020
- přehled pokladního plnění za 2019 https://www.mfcr.cz/cs/verejny-sektor/statni-rozpocet/plneni-statniho-rozpoctu/2019/mesicni-pokladni-plneni-2019-34199 s odkazy na tiskové zprávy, URL excelů v 2019 bohužel nejsou konzistentní
- výkaz zdrojů a užití prostředků SR v OSS https://www.mfcr.cz/cs/verejny-sektor/rozpoctove-ramce-statisticke-informace/fiskalni-udaje/ustredni-vlada/organizacni-slozky-statu/2020/vykaz-zdroju-a-uziti-peneznich-prostredk-37685

# Národní účty

- [Satelitní účet veřejného sektoru](https://apl.czso.cz/pll/rocenka/rocenkavyber.gov_a?mylang=CZ) a [zde](https://apl.czso.cz/pll/rocenka/rocenkavyber.sat_vs), tabulka GOV_AGREGe20 Hlavní agregáty sektoru vládních institucí => náhrady zaměstnanců D1, i za subsektory
  - [časové řady](https://apl.czso.cz/pll/rocenka/rocenkavyber.sat_vs_cas?mylang=CZ) VS000205
  - zaměstnanci celkem i za veřejný sektor VS000103
- [Sektorové účty](https://apl.czso.cz/pll/rocenka/rocenkavyber.makroek_sektor)
  - účet tvorby důchodů: SS001302n19 Vládní instituce: účet tvorby důchodů: mzdy za subsektory
  - Zaměstnanci: M000152 Zaměstnanost celkem (úvazky na plnou pracovní dobu) podle sektorů (vládní, ne veřejný)
- [časové řady ukazatelů účtů výroby a tvorby důchodů](https://apl.czso.cz/pll/rocenka/rocenkavyber.socas) podle NACE + na konci tabulek jsou čísla i za sektor 13 (vládní)
  - TB001Z**: zaměstnanci

# Státní služba

- [výroční zprávy o státní službě 2016-2019](https://www.mvcr.cz/sluzba/clanek/vyrocni-zprava-vyrocni-zprava-o-statni-sluzbe.aspx) a [2020](https://www.mvcr.cz/sluzba/clanek/vyrocni-zprava-o-statni-sluzbe-za-rok-2020.aspx)
- systemizace při každé změně od 2019 https://www.mvcr.cz/sluzba/clanek/systemizace-sluzebnich-a-pracovnich-mist.aspx
- open data 
	- organizační struktura za celou státní služby [data](https://portal.isoss.cz/opendata/ISoSS_Opendata_OSYS_OSSS.xml), [katalog](https://data.gov.cz/datov%C3%A1-sada?iri=https%3A%2F%2Fdata.gov.cz%2Fzdroj%2Fdatov%C3%A9-sady%2F00007064%2F846439539)
	- obsazovaná služební místa [data](https://portal.isoss.cz/opendata/ISoSS_Opendata_EOSM.xml) [katalog](https://data.gov.cz/datov%C3%A1-sada?iri=https%3A%2F%2Fdata.gov.cz%2Fzdroj%2Fdatov%C3%A9-sady%2F00007064%2F255131823)

- [open data Státní služby](https://portal.isoss.cz/opendata/) a [v NKOD](https://data.gov.cz/datov%C3%A9-sady?poskytovatel=https%3A%2F%2Frpp-opendata.egon.gov.cz%2Fodrpp%2Fzdroj%2Forg%C3%A1n-ve%C5%99ejn%C3%A9-moci%2F00007064&kl%C3%AD%C4%8Dov%C3%A1-slova=ISoSS)


# Další zdroje

- MV ČR (2020) ["ANALÝZA STÁRNUTÍ ZAMĚSTNANCŮ VEŘEJNÉ SPRÁVY"](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwjWjbG5jvHwAhVEwKQKHZ2OAKwQFjAAegQIAhAD&url=https%3A%2F%2Fwww.mvcr.cz%2Fsoubor%2Fanalyza-starnuti-zamestnancu-verejne-spravy-2020-pdf.aspx&usg=AOvVaw1zJVRooNl3a7RMPIl11feO) 

  - je tam matice počtů věk x platová třída 5-16 zvlášť pro ústřední a ostatní orgány
  - též podíly představených na jednotlivých věkových skupinách

## Platové tabulky

- v excelu zveřejněno v příloze [webu MF o ISPSP](https://www.mfcr.cz/cs/o-ministerstvu/informacni-systemy/is-o-platech/)

# Zdroje o jednotlivých organizacích

## ČSSZ - open data o zaměstnancích 

- průměr a medián platů https://data.cssz.cz/web/otevrena-data/-/prumerny-plat-v-cssz
- systemizovaná místa a fluktuace https://data.cssz.cz/web/otevrena-data/-/systemizovana-mista-a-fluktuace-zamestnancu-cssz
- zaměstnanci dle vzdělání https://data.cssz.cz/web/otevrena-data/-/zamestnanci-cssz-dle-vzdelani

## Finanční správa

- [délka trvání poměru, časová řada](https://data.gov.cz/datov%C3%A1-sada?iri=https%3A%2F%2Fdata.gov.cz%2Fzdroj%2Fdatov%C3%A9-sady%2F00006947%2F7bc7d6fb2e616c1981283199d728b70f)
- [evidenční počty zaměstnanců ve finanční správě](https://data.gov.cz/datov%C3%A1-sada?iri=https%3A%2F%2Fdata.gov.cz%2Fzdroj%2Fdatov%C3%A9-sady%2F00006947%2F19cf44c9fd89438c5738c4f1cff2678b)
- [počet systemizovaných míst](https://data.gov.cz/datov%C3%A1-sada?iri=https%3A%2F%2Fdata.gov.cz%2Fzdroj%2Fdatov%C3%A9-sady%2F00006947%2F79d2b92981282337f1abf2b18c5dd120)

## Platy vysoce postavených úředníků

- [iRozhlas 2022](https://www.irozhlas.cz/zpravy-domov/mimoradne-odmeny-jana-malacova-ministerstva-premie-penize-bonus_2202050500_vtk) + [květen 2022](https://www.irozhlas.cz/zpravy-domov/platy-statnich-uredniku-mynar-ovcacek_2205231708_cen)
- [iRozhlas 2016 - jmenovité](https://www.irozhlas.cz/zpravy-domov/velky-prehled-ministerske-odmeny-za-rok-2016-kdo-data-taji-a-kdo-bez-problemu-zverejnuje-_201702070600_hmazancova)


# Mezinárodní

- [Worldwide Bureaucracy Indicators](https://datacatalog.worldbank.org/dataset/worldwide-bureaucracy-indicators) - obsahuje proměnné měřící "Public Sector Wage premium", viz skript `world-bureaucracy-salaries.R`
- Eurostat: [Civil Servants Remuneration](https://ec.europa.eu/eurostat/web/civil-servants-remuneration): counts of central gov employees with indices of pay (gross and net) collected for the purposes of setting EU salaries; dataset available in Eurostat database as [PRC_REM_CS]
(https://ec.europa.eu/eurostat/databrowser/view/prc_rem_cs/default/table?lang=en).
